hashes_cache_dir: ../.obsankipy
vault:
  dir_path: ../
  medias_dir_path: ../800 - Media
  exclude_dotted_dirs_from_scan: true # excludes directories that start with a dot
  exclude_dirs_from_scan:
    - 000 - MOCs
    - 900 - Templates
  file_patterns_to_exclude:
    - ".*" # excludes files that start with a dot
    - "_*" # excludes files that start with an underscore
notetypes:
  Obsidian:
    regexes:
        - '^#+ (?:(?:Abkürzung *\n+((?:(?:^[^\n#].{0,2}$|^[^\n#].{3}(?<!<!--)(?<!\!Mer).*)\n*)+))|(?:Synonym *\n+((?:(?:^[^\n#].{0,2}$|^[^\n#].{3}(?<!<!--)(?<!\!Mer).*)\n*)+))|(?:Definition *\n+((?:(?:^[^\n#].{0,2}$|^[^\n#].{3}(?<!<!--)(?<!\!Mer).*)\n*)+))|(?:(.+) *\n+(?:(\!\[\[.*\]\])\n*)?((?:(?:^[^\n#].{0,2}$|^[^\n#].{3}(?<!<!--)(?<!\!Mer).*)\n*)+)))(?:!Merke((?:\n(?:^[^\n#].{0,2}$|^[^\n#].{3}(?<!<!--).*))+))?'
    fields:
      - Context: CONTEXT
      - Abkürzung: 1
      - Synonym: 2
      - Definition: 3
      - Sonstige Frage: 4
      - Bild: 5
      - Sonstige Antwort: 6
      - Merkhilfe: 7
      - Link: LINK
  Altklausuren:
    regexes:
    - '^Q:(?: *)((?:.+\n)*)\n*T:(?: *)((?:.+\n)*)\n*A:(?:.*\n)((?:.+\n)*)\n*E:(?:.*\n)((?:.+\n)*)\n*S:(?: *)(.+(?:\n(?:^.{1,3}$|^.{4}(?<!<!--).*))*)'
    fields:
      - Question: 1
      - Type: 2
      - Answer: 3
      - Explanation: 4
      - Solution: 5
      - Link: LINK
      - Context: CONTEXT
globals:
  anki:
    deck_name: Knowledge
    tags:
      - Obsidian
    url: http://localhost:8765